# Example services.yaml entry

# Service ID
siren:
  # Service name as shown in UI
  name: Set Siren
  # Description of the service
  description: Sets the siren status.
  # If the service accepts entity IDs, target allows the user to specify entities by entity, device, or area. If `target` is specified, `entity_id` should not be defined in the `fields` map. By default it shows only targets matching entities from the same domain as the service, but if further customization is required, target supports the entity, device, and area selectors (https://www.home-assistant.io/docs/blueprint/selectors/). Entity selector parameters will automatically be applied to device and area, and device selector parameters will automatically be applied to area.
  target:
  # Different fields that your service accepts
  fields:
    # Key of the field
    command:
      # Field name as shown in UI
      name: Command
      # Description of the field
      description: Status setting command
      # Whether or not field is required (default = false)
      required: true
      # Advanced fields are only shown when the advanced mode is enabled for the user (default = false)
      advanced: true
      # Example value that can be passed for this field
      example: "off"
      # The default field value
      default: "on"
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control the input UI for this field
      selector:
        select:
          options:
            - "off"
            - "on"

# Service ID
output:
  # Service name as shown in UI
  name: Set Output
  # Description of the service
  description: Switch an output on/off.
  # If the service accepts entity IDs, target allows the user to specify entities by entity, device, or area. If `target` is specified, `entity_id` should not be defined in the `fields` map. By default it shows only targets matching entities from the same domain as the service, but if further customization is required, target supports the entity, device, and area selectors (https://www.home-assistant.io/docs/blueprint/selectors/). Entity selector parameters will automatically be applied to device and area, and device selector parameters will automatically be applied to area.
  target:
  # Different fields that your service accepts
  fields:
    # Key of the field
    id:
      # Field name as shown in UI
      name: Id
      # Description of the field
      description: Output number
      # Whether or not field is required (default = false)
      required: true
      # Advanced fields are only shown when the advanced mode is enabled for the user (default = false)
      advanced: true
      # Example value that can be passed for this field
      example: 1
    # Key of the field
    command:
      # Field name as shown in UI
      name: Command
      # Description of the field
      description: Status setting command
      # Whether or not field is required (default = false)
      required: true
      # Advanced fields are only shown when the advanced mode is enabled for the user (default = false)
      advanced: true
      # Example value that can be passed for this field
      example: "off"
      # The default field value
      default: "on"
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control the input UI for this field
      selector:
        select:
          options:
            - "off"
            - "on"
